### ISSUE TITLE
Moe Theme Switcher has disappeared!

### ISSUE THREAD

**Issue by pegzmasta** [kuanyui/moe-theme.el#107]
I still use `moe-theme-switcher.el` in my init file.  Can you add it back into the repository?

**Comment by kuanyui** [comment]
Undeleted. Please check it.

2020年9月17日(木) 11:43 Michael Pagan <notifications@github.com>:

**Comment by pegzmasta** [comment]
Thanks!

**Comment by tangxinfa** [comment]
Please disable it by default, we install it not means we will activate it
instantly, there is a package
[circadian](https://github.com/guidoschmidt/circadian.el) did theme switch for
any themes.

**Comment by kuanyui** [comment]
This should not enabled by default. I don't sure what you are talking about.

**Comment by tangxinfa** [comment]
The `moe-theme-switcher` is automatically activated yesterday, theoretically
there is not way to activate it, except load it manually.

**Comment by kuanyui** [comment]
I have not modified this project for quite a long time and doesn't encounter this issue, If occurs, it may be the changes of package.el or the setting of your package manager. I really don't know how to fix this.

**Comment by tangxinfa** [comment]
I have figured out why the `moe-theme-switcher` automatically activated:

1, Press "C-h v" to describe-variable

2, Input "switch-"

3, Then the completion framework(I use [mct](https://github.com/protesilaos/mct)) trigger the auto load of `moe-theme-switcher`

And the `moe-timer` is setup to switch theme automatically.

**Comment by tangxinfa** [comment]
~.emacs.d/elpa/moe-theme-20220111.1220/moe-theme-autoloads.el

This is the generated autoloads relate to moe-theme-switcher:

    ;;;***
    
    ;;;### (autoloads nil "moe-theme-switcher" "moe-theme-switcher.el"
    ;;;;;;  (0 0 0 0))
    ;;; Generated autoloads from moe-theme-switcher.el

    (register-definition-prefixes "moe-theme-switcher" '("convert-time-format-of-sunrise-and-sunset" "get-sunrise-sunset-string" "moe-" "switch-"))

**Comment by kuanyui** [comment]
That seems the reason is MELPA/ELPA's mechanism, and I'm really not familiar to it... (since long long time ago...). Sorry. If you know how to fix this (or try to fix this), please consider to open a PR.

**Comment by jmickelin** [comment]
The very first step would be to put the top-level logic of `moe-theme-switcher.el` into a function, so that it has to be explicitly enabled. The issue is that `package.el` always loads all files in a package when unpacking them (for the sake of byte-compiling them). This can't be disabled.

The second issue is, like @tangxinfa mentioned above, that every file ends up sharing the same autoloads, which get loaded arbitrarily by all kinds of interactions in Emacs, so the top level code comes back to bite you even if you do your hardest to unload the module (e.g. with `unload-feature`).

Here is a quick and dirty attempt at it:
```elisp
(defun moe-theme-switcher-enable ()
  "Set up timers for automatically switching between dark and light
moe-theme."
  (interactive)
  (when (and
         (boundp 'calendar-longitude)
         (boundp 'calendar-latitude)
         moe-theme-switch-by-sunrise-and-sunset)
    (setq moe-convert-time-format-timer
          (run-with-timer 0 (* 60 60 24)
                          'convert-time-format-of-sunrise-and-sunset)))

  (setq moe-timer (run-with-timer 0 (* 1 60) 'moe-theme-auto-switch)))

;; [FIXME] A minor-mode to enable/disable moe-theme-switcher
(defun moe-theme-switcher-disable ()
  "Turn off the timers for automatically switching between dark and light
moe-theme."
  (interactive)
  (when (and (boundp 'moe-convert-time-format-timer)
             (timerp moe-convert-time-format-timer))
    (cancel-timer moe-convert-time-format-timer))
  (cancel-timer moe-timer))
```

Like the `FIXME` indicates, this can be wrapped up into a minor-mode for convenience:

```elisp
(define-minor-mode moe-theme-switcher-mode
  "Enable the moe-theme-switcher, to automaticaly change between the light 
and dark variants."
  :lighter " Moe"
  :global t
  (if moe-theme-switcher-mode
      (moe-theme-switcher-enable)
    (moe-theme-switcher-disable)))
```

Users can then enable it in their config like with other minor-modes, like so:
```elisp
(moe-theme-switcher-mode 1)
```

or call `M-x moe-theme-switcher-mode` to toggle it interactively.

I will try to create some PRs in the coming days. Future readers should remind me if I seem to have forgotten :)

**Comment by jmickelin** [comment]
Created #132. It will be a breaking change, since just loading `moe-theme-switcher.el` will no longer be enough to enable it -- It must be done explicitly by running `(moe-theme-switcher-mode 1)` or similar.
