### ISSUE TITLE
Update title-resizing variable names in the README file

### ISSUE THREAD

**Issue by lhy7889678** [kuanyui/moe-theme.el#116]
In the current README file, the title-resizing variable names (such as `moe-theme-resize-org-title`) have the corresponding language names before `title`. Yes, they used to be named like this. However, now their names have been updated, which has swapped the order (`moe-theme-resize-title-org`). Could we update that in the README file?

(I had struggled with my init file for half an hour, wondering why title-resizing was not properly functioning. Finally I did a `C-h v` and the auto-completion helped me...)

**Comment by kuanyui** [comment]
Sorry.... I'm too tired to maintain this document, and sorry for wasting your time to figure out where the problem is...

But I really has been burnt out on this project, and my free time become less and less these years. I am still using this moe-theme everyday (because use Emacs every), so if need I still update this package if need (for example, latest Magit 3.x has lots of new faces compared to 2.x), but I really has no more passion to fix the other part that I don't need or not using.

And the last but not the least thing is, this is a FLOSS project, if you've found where the problem is, feel free to make a PR. Happy hacking!
